### ISSUE TITLE
Set BuildingGroup::RecordWall & RecordTube LOCATION argument as const

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/Outpost2DLL#14]
Can we set BuildingGroup::RecordWall and BuildingGroup::RecordTube's location parameter as const?

Update to:
```C++
void RecordTube(const LOCATION& tubeLocation);
void RecordWall(const LOCATION& location, map_id wallType);
```

It would improve readability when passing by reference.

Thanks,
Brett

**Comment by DanRStevens** [comment]
That's likely to change the name mangling and break linking to Outpost2.exe. You can try it an see. Likely any code calling the updated method signatures will produce link errors.

Any wrapper methods could accept parameters by const-reference, and then `const_cast` before calling. Really though, for a small struct like this, it's often best to just pass by value. (Which would also likely change the name mangling).

**Comment by Brett208** [comment]
Okay, it is already passed by reference, just not const reference. This makes it misleading because I would assume it is somehow changing the value of the passed in LOCATION if not marked const.

-Brett

**Comment by DanRStevens** [comment]
Ahh, I think I accidentally added my answer to this elsewhere. You're right, it can be misleading. Though usually I just assume they forgot `const`, or the programmer wasn't aware enough about const-correctness to know to add it.

In terms of changing parameter declarations in Outpost2DLL, I don't think we can do that. Any changes are likely to break function linking due to name mangling differences.

**Comment by DanRStevens** [comment]
We should probably close this as not fixable. A shame though, it would have been a nice change.

**Comment by DanRStevens** [comment]
Closing this as unfixable.
